In [1]:
import numpy as np

In [2]:
a = np.array([[2,3,4],[1,9,7]])
print(a)

[[2 3 4]
 [1 9 7]]


In [5]:
a.shape

(2, 3)

In [6]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [11]:
c = np.full((2,2),np.pi)
print(c)

[[3.14159265 3.14159265]
 [3.14159265 3.14159265]]


In [9]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
e = np.random.random((3,5))
print(e)

[[0.23249198 0.60089201 0.22940417 0.67493138 0.89331118]
 [0.18204571 0.66952238 0.69137061 0.83109918 0.94557837]
 [0.2055733  0.42986704 0.30060777 0.3709456  0.47101916]]


In [16]:
f = np.arange(0,50,7)
print(f)

[ 0  7 14 21 28 35 42 49]


In [18]:
g = np.linspace(0,50,7)
print(g)

[ 0.          8.33333333 16.66666667 25.         33.33333333 41.66666667
 50.        ]


In [21]:
h = np.full((3,4), np.pi, dtype = 'int64')
print(h)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [22]:
i = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
j = i[:2, 1:3]
print(i)
print(j)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [28]:
print(i.max())

12


In [29]:
print(i.max(axis = 1))

[ 4  8 12]


In [33]:
x = np.array([[1,2],[3,4]])
print(x)
y = np.array([[12,25],[5,90]])
print(y)
print(x*y)

[[1 2]
 [3 4]]
[[12 25]
 [ 5 90]]
[[ 12  50]
 [ 15 360]]


In [34]:
print(x.dot(y))

[[ 22 205]
 [ 56 435]]
