<a href="https://colab.research.google.com/github/DeepankJain/MachineLearning/blob/master/Support%20Vector%20Machine/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#importing libraries
import pandas as pd
import numpy as np
import seaborn as sns

In [0]:
#loading the dataset
df = sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [0]:
from sklearn.model_selection import train_test_split as tts
train, test = tts(df, test_size = 0.2)

In [0]:
train_x = train.loc[:, train.columns != 'species']
test_x = test.loc[:, test.columns != 'species']
train_y = train['species']
test_y = test['species']

In [0]:
from sklearn.svm import SVC
model = SVC(kernel = 'poly', degree = 8)
model.fit(train_x, train_y)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
test_pred = model.predict(test_x)

In [0]:
result = pd.DataFrame({'Actual': test_y,
                       'Predicted': test_pred})
print(result)

         Actual   Predicted
3        setosa      setosa
29       setosa      setosa
22       setosa      setosa
55   versicolor  versicolor
26       setosa      setosa
17       setosa      setosa
11       setosa      setosa
143   virginica   virginica
57   versicolor  versicolor
135   virginica   virginica
8        setosa      setosa
125   virginica   virginica
6        setosa      setosa
68   versicolor  versicolor
107   virginica   virginica
106   virginica  versicolor
122   virginica   virginica
28       setosa      setosa
111   virginica   virginica
97   versicolor  versicolor
134   virginica  versicolor
33       setosa      setosa
132   virginica   virginica
16       setosa      setosa
121   virginica   virginica
102   virginica   virginica
9        setosa      setosa
116   virginica   virginica
45       setosa      setosa
27       setosa      setosa


In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(test_y, test_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.67      1.00      0.80         4
   virginica       1.00      0.83      0.91        12

   micro avg       0.93      0.93      0.93        30
   macro avg       0.89      0.94      0.90        30
weighted avg       0.96      0.93      0.94        30



In [0]:
print(confusion_matrix(test_y, test_pred))

[[14  0  0]
 [ 0  4  0]
 [ 0  2 10]]
